Add App.java
YangJungho2214/Study_01 pull request #1
Opened 2024-07-05 08:28 UTC by YangJungho2214

이번에는 성공했으면 좋겠네요!

코멘트에 달려있는 부분은 제가 좀 이해를 하고 만들어야 될꺼 같아서 더 공부해 보겠습니다!

근데 아직 if문에 *가 들어가서 매소드에서 3 * 1 을 입력하면 인수갯수 에러로 왜 들어가는지 파악을 못 하고 있습니다!

대체법으로 if문에 *가 아닌 연산자가 x일때 가능하게 해두었습니다.

2024-07-05 09:29 UTC, junforjun requested changes

2024-07-05 09:29 UTC, junforjun commented on src/App.java
> +import java.util.Scanner;
불필요한 임포트

2024-07-05 09:29 UTC, junforjun commented on src/App.java
> +// -*- coding: utf-8 -*-
패키지는 선언해줘

2024-07-05 09:29 UTC, junforjun commented on src/App.java
> +            System.out.println("인수의 갯수가 모자랍니다. 3개를 입력해주세요.");
모자른지 아닌지? 

사양서가 틀렷다는 가정을 해봐

2024-07-05 09:29 UTC, junforjun commented on src/App.java
> +            System.out.println("첫번째 세번째 인수가 숫자가 아닙니다.");  //첫번째 세번째 인수가 숫자가 아니면 에러
코멘트는 한줄로 위에 적도록

2024-07-05 09:29 UTC, junforjun commented on src/App.java
> +        } catch (NumberFormatException e) {
트라이 캐치문은 좋은데

인트 범위를 넘어서는놈도 에러날걸?

2024-07-05 09:29 UTC, junforjun commented on src/App.java
> +        } else if (plus == 'x') { //else if (plus == '*') { 로 했을시 [인수의 갯수가 모자랍니다. 3개를 입력해주세요.] 에러가 발생 해결 방법 못 찾음.. 이스케이프??
곱하기는 이스케이프\

2024-07-05 09:29 UTC, junforjun commented on src/App.java
> +        } else if (plus == 'x') { //else if (plus == '*') { 로 했을시 [인수의 갯수가 모자랍니다. 3개를 입력해주세요.] 에러가 발생 해결 방법 못 찾음.. 이스케이프??
문자열은 " "

2024-07-05 09:29 UTC, junforjun commented on src/App.java
> +            return;
에러일때는 System.exit(1)로 이상종료

return하게되면 0으로 종료코드가 나온다

검색해봐

2024-07-06 01:48 UTC, YangJungho2214 commented on src/App.java
> +import java.util.Scanner;
삭제완료

2024-07-06 01:49 UTC, YangJungho2214 commented on src/App.java
> +// -*- coding: utf-8 -*-
패키지 선언 완료

2024-07-06 01:49 UTC, YangJungho2214 commented on src/App.java
> +            System.out.println("인수의 갯수가 모자랍니다. 3개를 입력해주세요.");
인수가 모자를때와 많을때를 따로 나누겠습니다.

2024-07-06 01:49 UTC, YangJungho2214 commented on src/App.java
> +            System.out.println("첫번째 세번째 인수가 숫자가 아닙니다.");  //첫번째 세번째 인수가 숫자가 아니면 에러
확인 완료

2024-07-06 01:50 UTC, YangJungho2214 commented on src/App.java
> +        } catch (NumberFormatException e) {
타입을 long으로 선언하고 int의 범위가 넘으면 에러가 나게 수정 할 예정입니다.

2024-07-06 03:35 UTC, YangJungho2214 commented on src/App.java
> +        } else if (plus == 'x') { //else if (plus == '*') { 로 했을시 [인수의 갯수가 모자랍니다. 3개를 입력해주세요.] 에러가 발생 해결 방법 못 찾음.. 이스케이프??
else if (plus == '*') 로 수정 후 실행 할 때 java first.App 4 \* 8 이스케이프 넣어서 실행 한다는 건가요?
이렇게 해도 결과는 계속 오류로 빠지네요ㅠ

2024-07-06 03:37 UTC, YangJungho2214 commented on src/App.java
> +        } else if (plus == 'x') { //else if (plus == '*') { 로 했을시 [인수의 갯수가 모자랍니다. 3개를 입력해주세요.] 에러가 발생 해결 방법 못 찾음.. 이스케이프??
} else if (plus == "x") 이렇게 하면 char 타입이라 컴파일시 오류가 발생하고 있습니다ㅠ

2024-07-06 04:29 UTC, junforjun commented on src/App.java
> +        } else if (plus == 'x') { //else if (plus == '*') { 로 했을시 [인수의 갯수가 모자랍니다. 3개를 입력해주세요.] 에러가 발생 해결 방법 못 찾음.. 이스케이프??
문자열 판정할때 "/*"

2024-07-06 04:30 UTC, junforjun commented on src/App.java
> +        } else if (plus == 'x') { //else if (plus == '*') { 로 했을시 [인수의 갯수가 모자랍니다. 3개를 입력해주세요.] 에러가 발생 해결 방법 못 찾음.. 이스케이프??
문자는 기본String을 써야지 두글자 이상이면 젼환할때 에러날거니..

2024-07-09 05:57 UTC, junforjun requested changes
2차레뷰 완료

2024-07-09 05:57 UTC, junforjun commented on src/first/App.java
> +                System.out.println("인수의 갯수가 많습니다. 인수는 3개를 입력해주세요.");
인덴트

2024-07-09 05:57 UTC, junforjun commented on src/first/App.java
> +                System.out.println("첫번째 세번째 인수가 숫자가 아닙니다.");
소수점은?

2024-07-09 05:57 UTC, junforjun commented on src/first/App.java
> +        int num1 = (int) lnum1;
롱으로 받아서 왜int임??

2024-07-09 05:57 UTC, junforjun commented on src/first/App.java
> +        char plus = args[1].charAt(0);
+-입력하면??

2024-07-09 05:57 UTC, junforjun commented on src/first/App.java
> +        long answer = 0;
BigDecimal이라면 오버플로에서 안전

2024-07-09 06:21 UTC, YangJungho2214 commented on src/first/App.java
> +                System.out.println("인수의 갯수가 많습니다. 인수는 3개를 입력해주세요.");
수정하였습니다.

2024-07-09 06:22 UTC, YangJungho2214 commented on src/first/App.java
> +        long answer = 0;
확인했습니다.

2024-07-09 06:28 UTC, YangJungho2214 commented on src/first/App.java
> +        char plus = args[1].charAt(0);
첫번째 연산자만 가지고 오기 때문에 첫번째 연산자로만 계산이 됩니다. 
연산자가 2개가 들어오면 ERR가 발생하게 하겠습니다.

2024-07-09 06:58 UTC, YangJungho2214 commented on src/first/App.java
> +                System.out.println("첫번째 세번째 인수가 숫자가 아닙니다.");
BigDecimal를 이용해서 소수점도 가능하도록 하였습니다.

2024-07-16 13:44 UTC, junforjun approved these changes

2024-07-16 13:44 UTC, merged